language: java
jdk:
  - oraclejdk8

sudo: false

env:
  - GROUP=index
## This is just to determine the time to do the background build.
#  - GROUP=nothing

script: travis_wait 120 ./.travis-build.sh $GROUP

git:
  depth: 3
